# Generated by Django 4.2.11 on 2024-03-12 10:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Телефон должен состоять из цифр', regex='^[0-9]*$')])),
                ('email', models.EmailField(max_length=254)),
                ('project_name', models.CharField(max_length=300)),
                ('project_description', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.project')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.project')),
            ],
        ),
    ]
