# Generated by Django 4.2.11 on 2024-03-14 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_project_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(default='', max_length=3, validators=[django.core.validators.RegexValidator(message='Код должен состоять из цифр', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='phone',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Телефон должен состоять из цифр', regex='^[0-9]*$')]),
        ),
    ]
