# Generated by Django 4.2.11 on 2024-03-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_project_email_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='<django.db.models.fields.related.ForeignKey>/files/'),
        ),
    ]
