# Generated by Django 4.2.11 on 2024-03-17 16:07

from django.db import migrations, models
import vote.models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=vote.models.get_file_upload_path),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
