# Generated by Django 4.2.11 on 2024-03-19 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_alter_file_file_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(default='', max_length=2, validators=[django.core.validators.RegexValidator(message='Код должен состоять из цифр', regex='^[0-9]*$')]),
        ),
    ]
