# Generated by Django 4.2.11 on 2024-03-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_alter_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_idea',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
